name: Maven Package with Tests

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'  # or 'temurin'
        
    - name: Build with Maven
      run: mvn -B package --file test-common-email/pom.xml
      
    - name: Test with Maven
      run: mvn clean test
